### ISSUE TITLE
Arcane tomes do not start with complete translations.

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#13895]
This seems bad.

It takes ten minutes max to complete research once a cultist that knows what they are doing get Self or any two other words. For cultists, word research just makes them dick around and wait while that one person delivers hopefully before they go braindead due to IRL reasons or what ever, if their plans depend on more sophisticated uses of runes which I believe should be encouraged. For noncultists, word research just lengthens the amount of time they gotta wait until something happens, other than maybe poke and convert, when the cultist shenanigans could be so much more in the meantime.

This is a cult buff, sure. But I think it is better for most or all parties involved if the wait for research stopped existing.

**Comment by jknpj** [comment]
what the fuck

**Comment by SonixApache** [comment]
there is no yred in team

**Comment by Exxion** [comment]
I get where you're coming from. Unnecessary tedium that adds nothing isn't good. But I don't really think this is an example of unnecessary tedium.

If you just want research to be more interesting, we could arrange it into a kind of tier system. Example:
The cultists start with several tier 1 words, like they already do. Most existing runes are made entirely of tier 1 words.
For each tier 2 word, there is one rune consisting of two tier 1 words and a tier 2 word. Such runes actually have some cost to draw (like a shit ton of blood or something), so that you can't just turbo speed power through them. You actually have to gradually "unlock" them throughout the round. They are also more powerful, of course.
For each tier 3 word, there is one rune consisting of two tier 2 words and one tier 3 word. These require a significant cost to draw (like a sacrifice, for example). And, of course, they are quite powerful.
Tear Reality is made entirely of tier 3 words.
As far as progression goes, whether or not there are other arrangements of tiered runes isn't really important, as long as these ones exist.

**Comment by ShoMek** [comment]
@Exxion Well...consider this: currently, I'd say that if you are extremely lucky, given 10 cultists, only 3 know what they are doing.
At round start, being lucky means 1 of the starting 3-4 knows how to do research.

Again, that's if you are lucky. In most rounds, NO ONE does research. Period.

No, I do not think tomes should start with all words, but your proposal is just a plain nerf. It sounds like you are increasing the amount of requirements and knowledge, when in my opinion those things are already a problem.

I think what cult needs is a better way to communicate. Like what revsquad got.
Maybe using the communicate rune for the first time unlocks something within your body that allows you to communicate more frequently. Something similar.

**Comment by jknpj** [comment]
maybe some kind of bloody tatoo that works like a communicate rune?

**Comment by gbasood** [comment]
I'll say that making cart startup easier is definitely *not* a way to resolve anything about cult.
But I like @jknpj 's body tattoo idea. Better ways to communicate for cult aren't necessarily bad but they should carry some form of risk, like a noticeable tattoo. Communicating right now is only risky because you might get caught laying out a rune or using a talisman, and only because both of those are cumbersome and take time

**Comment by ShoMek** [comment]
If you use imbue talisman rune (we could change name to imbue rune or something) while being on top of it with a communicate rune next to it, you imbue the communicate rune to your forehead. 

What about that? Should it have a cooldown & be a skill? Or should it unlock something like a cultist chat? Similar to ":g". What about having a limited amount of uses?

I'm just throwing ideas, I really like the tattoo idea. Maybe recycling functions like the imbue talisman rune is not so good and we actually want a new feature. I am not sure.

**Comment by Exxion** [comment]
I haven't played cult in quite a while, but I don't think I've ever been a roundstart cultist and not had somebody do research
That said, yeah, it's rarely more than 2 people who know what they're doing, so additional complexity may not be the best idea

**Comment by kol1th** [comment]
I agree with doing away with research. It does nothing but promote powergaming a little platform in space and making constructs. 

You can and will be hunted down if you're not in your department doing whatever, which means you're an antag. 

Doing away with research would alleviate this. It would also alleviate the "converted with no book/no words" thing that also happens constantly. 

Cult tends to go like this:

* The cultists are found early, hunted down, and congratulations it's now extended.
* One cultist does all of the work on a platform in space/fuck all middle of nowhere, and sends ghosts to kill everyone.
* It's lowpop, no security, no chaplain, and nobody can stop the cult, and they win nearly by default.

**Comment by Blithering** [comment]
Manifest ghost spam could be limited by adding the same timer you get when you die as a mouse to being resummoned, and adding random switching between burn and brute damage taken to prevent diona infinitely self healing the combined runes of an undead army. And I still advocate giving cultists a spell to summon a tome to make it possible to ditch your gear and throw of sec without effectively ending your involvement.

**Comment by Shadowmech88** [comment]
What if we balanced it so that different races had different advantages and disadvantages within a cult?
Let diona continue to act as summoning tanks, but prevent them from drawing runes from their own blood since they have `NO_BLOOD`. Make them have to get ahold of a beaker of blood or something to do it.

**Comment by AI-is-rogue** [comment]
Dionaea use their sap or whatever the green stuff in trees is called, to draw their runes. It's also what comes out of them when they slam against a wall.

**Comment by kernikov** [comment]
CLOCK
U
L
T

**Comment by uazuaz** [comment]
then dionaea should take a lot more time to draw a rune.

**Comment by yclatious** [comment]
What if meditation could grant you a word? 

Those that could be absent and wouldn't be missed if not doing their work could be meditating and after a certain amount of time, could get a word, maint is already isolated and with several nooks to hide in, some waiting time wouldn't hurt anyone, and even if not for the word research itself, why not make it so anyone who managed to get away for a while could meditate and get a book instead of the last cultist being alone and without a book to be a cultist with?

**Comment by kol1th** [comment]
;SEC THERES A GUY MEDITATING IN MAINT HES A CULTIST

**Comment by Blithering** [comment]
Have it so that new convertees have a chance of learning a new word when they're culted. Cult is incentivised for recruiting, research doesn't have to be sitting in a box alone until you know the words and everyone's praising narnar

**Comment by gbasood** [comment]
also just so we can all see
this is all recorded cult games since I implemented stats
![cultstats](http://i.imgur.com/c8MJCB9.png)
and this is last month
![cultstats2](http://i.imgur.com/LM2dDl9.png)

**Comment by Fruktlimpa** [comment]
@gbasood Got a link to that shit? Looks interesting.

On topic.
Cult research is very odd at the moment. Like Kolith said and many others, very few starting cultists know what the fuck they are doing and you have to bet on one of them actually knowing how to research words to get anywhere.
Hopefully everyone does share their words and you can fuck off into space and spend those 15 minutes researching all the words and PRAY that no other cultist fucked up during that time, blowing your cult wide open and making the game 10x as hard.

They probably shouldn't be fully unlocked but maybe new convertees get to know a word when they get converted? This would encourage early conversion and cult activity while at the same time giving you words.

**Comment by yclatious** [comment]
@kol1th Id purposefully start meditating in maint as a religious gimmick just to anti meta to be honest, and its not like maint is hard to hide in or that populated.

**Comment by gbasood** [comment]
@Fruktlimpa http://stats.ss13.moe/globalstats

**Comment by DeityLink** [comment]
As far as I'm concerned, this is now fixed.
