### ISSUE TITLE
Bagel issue where I just keep a checklist so I dont forget shit

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#14018]
Hi this is happening
![donutmax](https://cloud.githubusercontent.com/assets/3959840/23494324/056b4a50-fec7-11e6-9750-a2fb61d3e402.png)

constant W I P

Checklist
Current Todo list
- [x] Most of the mapping
- [ ] Make work?

**Comment by Kurfursten** [comment]
👍 For telescience adjacent to paramedic office

Soon

**Comment by Shadowmech88** [comment]
I have a .dmm with a completely 1:1 reconstructed, tiled, and windowed Donutstation2, if you'd like.
Of course, it'd only be useful if you planned on expanding/updating it, rather than just making a new one from scratch in a donut shape.

**Comment by Zth--** [comment]
I love hydroponics.

I like the bar idea but I don't think it's well executed

**Comment by CptWad** [comment]
too late for that shadowmech
far too late

If you mean the floortiles, then no I am not changing them.
Otherwise, elaborate

**Comment by Ephx1** [comment]
Might wanna add cameras to holodeck proper.

**Comment by CptWad** [comment]
Did we add them to the newholodecks in all maps or is that not happening?

**Comment by mtpowell** [comment]
Needs a morgue

**Comment by CptWad** [comment]
Its in the chapel

**Comment by mtpowell** [comment]
Yea but there's only two caskets for cloning, anymore bodies would overflow into the chapel and rarely if ever be checked to clone.

**Comment by Shadowmech88** [comment]
What about putting a camera inside the chapel's morgue that's linked to a console in Genetics, so doctors could glance at it and see if anyone needs cloning without having to walk to the chapel every time?

**Comment by Kurfursten** [comment]
Some more thoughts

>Way way way too many 1-tile wide hallways, a lot of rooms are weirdly cramped while others are ballooned out
>Unguarded, no-camera, single-airlock-straight-into-maint room to sabotage tcoms
>No pumps on the mixing chamber
>Bhangometer restricted to RD
>Two free boxes of metal foam grenades
>Every single department gets its own cafe dispenser, full snack machine, and starting box of food just in case Service needed to be a little more irrelevant - bar is actually less equipped than engineering or medical to serve drinks
>Why so many empty vending machines in the main halls?
>Don't forget Trader dock + ERT dock + Salvage Shuttle dock
>There's no reason to set the rad collectors a tile back, proximity matters
>Gee Bill, how come your mom lets you have four airlocks between the hallway and central engineering? Five to get to the SMES, even. That's nearly double Box or Deff, and more than Meta (two non-public doors plus a windoor). I like keeping out glovetide as much as the next guy but this much airlock slowdown is going to make me want to enter through that two-airlock passage from maint every time.
>It looks like you're trying to faithfully rebuild Donut2, but let me tell you now: disposal not near cargo is a mistake.
>Only one starting engine + nowhere to expand easily from engineering = angry engineers
>Virology airlock controller is in the waiting room not in the final chamber
>Your theater disposal chute is comically long
>I'm not sure you can stack pipes like that outside Tsci, make sure that gets tested
>Make sure to test your mule beacons, so they place packages the correct way (if it's wrong they can trap themselves by putting the package on the wrong side and cutting off their only escape)

Your biggest problem right now, which isn't a nitpick and is actually a huge fundamental problem, is the narrow cramped hallways. Delete some of the unnecessary restrooms since you have so many to make space if need be.

**Comment by Ephx1** [comment]
> narrow cramped hallways

You mean the locker room and EVA, right?

**Comment by CptWad** [comment]
@Kurfursten 
>I tried to keep shit two tiles wide at least. As for bloat specific critisim is welcome.
>Telecomms is motion sensor'd and there is a camera its just not showing under some other machinery since layers in the mapmaker are shit
![backroom](https://cloud.githubusercontent.com/assets/3959840/22982441/fc6d3fae-f353-11e6-84aa-5f1a1f47874c.png)
>Mixing chamber? Do you mean the borer pen? 
>Toxins will be located on the research station now for shit like the bangometer and such
>Fair point on food, however I will remind you that this is not the only map that does it
>Cargo gets vending packs they can drag around to said vending machines, my idea of having more for cargo to be responsible for
>I didnt
>They are the same distance? 
![324324](https://cloud.githubusercontent.com/assets/3959840/22982374/d6e98c60-f353-11e6-9825-140679e350db.png)
>Good point, the doors between engineering and the lobby will be cut
>Disposals WILL be near cargo
>That exists I just have not finished it
>They are on the same tile as the airlock, you can still access them
>intentional
>also fair point, fixed
>oh christ well I will make sure that works then


As for moving shit around it is possible, just be more specific.

**Comment by Aurx** [comment]
Are you moving xenobio to the 'roid?

**Comment by Kurfursten** [comment]
@CptWad Other maps have like one pizza in the department, the departmental breakrooms are getting a little too elaborate, I think.

As for the rad collectors on Box, they're not optimal either. There's just no reason for them to be back one tile needlessly.

Whether there's a motion camera back there or not, I still don't think the unguarded maint door for tcoms is a good idea, you can run in and turn that freezer to hot mode before the AI can even see you. That's enough to fry the stuff eventually.

I don't have time right now, but in a few hours I will show you the pressure points (areas where there is 1-wide hallway in a high traffic area). There are a bunch of these and they're probably going to be your biggest trouble in terms of getting this workable

**Comment by Kurfursten** [comment]
![untitled](https://cloud.githubusercontent.com/assets/9782036/22998529/cac546ba-f39c-11e6-8af5-80746b063031.png)

These are some of the weirder parts

**Comment by Kurfursten** [comment]
Another thing, if that's a borer room, I don't think it will work

Don't borer gets get smashed when they are thrown? Or was that removed?

**Comment by CptWad** [comment]
Yeah I replaced the excess food afyer your point.
I guess I will move the rad collectors 
As for telecomms, that's what I aimed for.
Thanks for the points, I'll do what I can
Disposals are for the eggs. Borers use the vents.
The idea of someone throwing a live borer in the trash is bizarre and funny to me for some reason.

**Comment by CptWad** [comment]
Oh right @Aurx yes

**Comment by CptWad** [comment]
Not to my knowledge it does, not that hard to fix either.

**Comment by Shadowmech88** [comment]
I don't believe putting a borer egg through disposals destroys it.

**Comment by CptWad** [comment]
![donutstation new](https://cloud.githubusercontent.com/assets/3959840/23007189/c39adb10-f3bb-11e6-878b-a7b0a53a0956.png)

Now with cargo action

**Comment by Kurfursten** [comment]
Virology vent, top side, disconnected from waste line
No easy-chute to send packages to the mail room in cargo
Engineering doors still need work
Make sure you check the input/output direction on the stacking and sorting machines in disposals
It's probably not necessary to have PDA machines so close together (arrivals, cargo lobby)
Won't the station holomap by the bar cover up the direction signs?

It's getting there. Sooner or later when this goes to PR you're going to have to sell people on all the stuff you've put in departments. Free random pills for medbay, random seeds for botany in addition to an animal and prebuilt chicken incubator (to say nothing of the pond but hell, some map needed to test it), baster for the chef, two boxes of metal foam grenades for engineering, lazarus injector for the science division, probably more stuff I didn't see. These aren't things I'm passing judgment on personally but I do believe it's something you have to be upfront about.

**Comment by Shadowmech88** [comment]
There doesn't seem to be a whole lot of interior maintenance compared to Donutstation2.
Also the empty space in the center of the station is much smaller.

**Comment by CptWad** [comment]
done
I have something like that I guess
FUCK I knew I forgot something
![image](https://cloud.githubusercontent.com/assets/3959840/23009437/d4d0df24-f3ca-11e6-963f-276f5167249f.png)
done
woops
also woops

**Comment by Ephx1** [comment]
It's more like a trodden on doughnut now.

**Comment by Aurx** [comment]
>yeah I had to cut most of the internal stuff.

What caused this?

**Comment by CptWad** [comment]
space constrictions mostly. the world in donutstation2 was old and small compared to all the crazy shit we have now

**Comment by Aurx** [comment]
Even after we doubled the size of z-levels?

**Comment by Shadowmech88** [comment]
I believe he might be trying to keep the same dimensions for the main hallway, rather than expanding the ring's size in order to accommodate the increased number of departments.

**Comment by CptWad** [comment]
Pretty much. Having a circle large enough to fit everything on the outside would likely make the "circumference" or hallway much longer.

**Comment by Shadowmech88** [comment]
Is it necessarily a bad thing to make the main hallway much longer?

**Comment by Kurfursten** [comment]
That reminds me Cpt. This last job you have to wait until the rest is done, and it sucks.

You have to open every airlock on the station to make sure there's not a wall or space turf under it.

**Comment by CptWad** [comment]
And test the powernet and the pipes and all the buttons and the disposal pipes and the mules and the shuttles and the cameras and the I'd access

**Comment by Kurfursten** [comment]
And of course don't forget you also need beacons for beepsky's patrol. You may want to ask for help with them, they're a little esoteric but easy enough to get a grip of. Only a handful of us ever bothered to learn how they function.

**Comment by Shadowmech88** [comment]
Couldn't you automate the airlock test by making a dummy item that runs 
```
for(var/obj/machinery/door/D in world)
    if(istype(get_turf(D), /turf/space))
        to_chat(world, "Airlock with space under it found at ([D.x], [D.y], [D.z])")
```
?

**Comment by CptWad** [comment]
I understand how the beacons work, ive done the whole mapping thing before. Its just making sure it works out in the end is what matters. 

I guess
also I think theres several of those on zlevel 2

**Comment by CptWad** [comment]
yay for progress
![donutstation new](https://cloud.githubusercontent.com/assets/3959840/23087253/81dbfcf0-f527-11e6-99c9-a551d2a24ed2.png)

**Comment by Ephx1** [comment]
Wow that chapel is fuckhuge.

**Comment by Shadowmech88** [comment]
It's looking more like a square or a triangle than a ring.

**Comment by Kurfursten** [comment]
Virology vent still broken
Incinerator vent missing

**Comment by Aurx** [comment]
>It's looking more like a square or a triangle than a ring.

Agreed.  

How did you plan this?

**Comment by Sprok0** [comment]
It looks like the main central hallway is the same dimensions as the original donut2's, but with all the new areas that are needed it bloats everything everywhere out.

**Comment by Shadowmech88** [comment]
I think it would look better if the main hallway was expanded to accommodate the new departments.

**Comment by CptWad** [comment]
It isn't a perfect circle. Attempting to turn it in to a perfect circle would be a waste because then you would have one FUCK HUGE long hallway. 
Im ressurecting donutstation not porting it. 
This is not exactly hard work but it's long and tedious work that I am willing to put towards a new map. You hopefully can understand that suggesting that I spend another month making a circular hallway LONGER just to hear people complain that the new hallway is to long is frustrating

**Comment by CptWad** [comment]
Also the vents are there I just forgot to update the picture in those two spots

**Comment by Kurfursten** [comment]
It will look more round when security gets added I'm sure

**Comment by CptWad** [comment]
![donutstation new](https://cloud.githubusercontent.com/assets/3959840/23328962/c1980d6e-fae2-11e6-96ce-90b8ab169315.png)
New update! 
With work, school and my own personal self hate being my only barriers I now only have two more areas to  flesh out before zlevel 1 is complete: Security and the rest of Engineering. 
And yes, the AI core is supercooled.

**Comment by Kurfursten** [comment]
*Atmospherics loops look unfinished. There are places the pipes have a manifold that goes nowhere, there's no reason you're ever going to want to drain the TEG waste into the main waste line because the heated gas will clog it up, and there's no room to build autism projects inside.
* People have complained that Deff AI Core is too much of a fortress, and this one is even more heavily defended. No map has a flasher by the upload computers which makes purging the AI impossible since it will flash you before you can upload your new laws. Deff's space turret system was already bad but you've taken that and added on super cooling which means you can't even attack the AI core without a hardsuit or you get hypothermia. Every map you can smash into the high risk modules, but this map you can't, you have to hack or deconstruct the walls.
* No radios in the confessional
* Chapel still seems weirdly constructed, all stretched out
* I'm pretty sure that photocopier in the IAA office is not accessible, same for the detective's filing cabinet
* The idea of being able to turn off the main distro loop for command and use the internal air is interesting (similar to brig atmos) but it's also connected to distro from the main door area so it doesn't actually do anything
* No vault door on the vault. I hope the vault has good loot too, because this one is by far the most fortified and inside the command wing.
* Gee CptWad, how come your map lets you have two head meeting rooms? Seems like you could do something better with that space.

Well, we'll see what comes of lower engineering and security. From there it's on to see your interpretation of the asteroid.

**Comment by Ephx1** [comment]
Uh Kurfurst, literally every map except Taxi has some sort of flasher by the AI upload

**Comment by Kurfursten** [comment]
Ay you're right. Haven't ever seen an AI use it instead of turrets.

The rest stands though.

**Comment by CptWad** [comment]
rad thanks for the input. I guess the outside turrets can go then, but I would like to keep the cooled AI core to see how well or poorly it does. I felt the added security was fair due to the many ways inside but I guess the extra outer turrets are unnecessary.
Confessional is just a table with curtains over it.
Tables don't block access to machines. I know this from experience (Law office and Detective Office)
woops on command Air.
As for total air loops, yeah I still need to finish much of it but I want to figure out how the rest of the station ends up then I will throw in the rest of the loops. Dont like vents under tables and shit.
That's more of a break room I guess? Its a side room that allows access to bridge maint/bridge.
What? That IS the vault door. As for loot its somewhat standard but I have ideas to buff it out later

**Comment by Kurfursten** [comment]
Does the vault door just have a weird icon on the map display? That's a regular command door like you use for the AI core

**Comment by Ephx1** [comment]
I'm not sure about removing the turrets outright, two broken windows and two beakers of thermite could pretty instantly kill an AI.
Maint, thermite to outside space, to small walkway, break window, thermite wall, shoot out windoor, run inside and hack up AI.

**Comment by Kurfursten** [comment]
I think he means just removing the space turrets, Ephx

Unless you still think that's too easy, but remember Box doesn't require a spacewalk at all, and only getting through 1 reinforced wall from the meeting room. Meta DOES require a space-walk but the entire structure is only one-wall thick after you smash out a glass window.

**Comment by Ephx1** [comment]
Well box also has several surrounding rooms that require a competent hacker or several other beakers of thermite, slowing down the process and giving a far longer timespan for the AI or borgs to react, if the surrounding rooms aren't already on fire. 

I've honestly never seen an AI core siege on Meta so I can't comment.

**Comment by Kurfursten** [comment]
Personally I think it's harder to deconstruct/thermite two reinforced walls and survive a space walk in that time than it is to get into the Box core. Go in through the meeting room - smashing the window and table or just remove the plastic flaps on the delivery window. You can also go via the bridge if the shutters haven't closed yet just by smashing windows at the front.

I don't know how it will be yet, but I don't think malf on Donut is going to be the hardest regardless. Longer walks around the station and the narrow concentration of the departments the AI needs to be watching the most (engineering, science, security) all in one place not far from their core makes their job much easier. Half the station can be safely ignored.

@CptWad That reminds me - need a bridge MULE delivery destination. Theater, too. And civilian airlocks every once in a while on the main hallway. They may be annoying but every station has them, and for good reason. Firelocks only appear AFTER an alarm has gone out, which means they only stop the problem from getting worse. Since the glass airlocks default to closed, they're better at stopping atmos problems. And on this singuloose station, that seems important.

**Comment by CptWad** [comment]
Bridge will have mule desto, also was unaware of a theater delivery, ill add that too. I will do deliverybot nonsense after the map is complete.
Current checklist is as follows
- [ ] Sec
- [ ] Aux Engineering
- [ ] Maintenance 
- [ ] Last Solars
- [ ] Hallway tweaks
- [ ] Last general tweaks (mulebots, destination routes, fixing shit people point out)
- [ ] zlevel 2
- [ ] zlevel 3
- [ ] zlevel 4
- [ ] zlevel 5
- [ ] zlevel 6

**Comment by Aurx** [comment]
That AI core is cripplingly vulnerable.  If you approach from the north maint, you can trivially block the only turret that can shoot at your approach, then there's literally nothing the AI can do about you.

**Comment by SangriaMonkey** [comment]
:ok_hand:

**Comment by CptWad** [comment]
![donutmax](https://cloud.githubusercontent.com/assets/3959840/23494324/056b4a50-fec7-11e6-9750-a2fb61d3e402.png)
donezo

**Comment by Aurx** [comment]
Any asshole with a single dose of thermite or an RCD, a spacesuit, and tools can dunk that AI and there is literally nothing the AI can do to stop them.  

Also not a fan of the penned in shuttles and enclosed botanytumor.

**Comment by Kurfursten** [comment]
* sme door?
* evidence room by maint is asking for trouble
* no perma? or is that where the shuttle is for?
* I think you should get some serious feedback from longtime security players on that brig layout. There's no natural congregation area, and the cells are set so far back from the entrance. Not to mention the sheer number of doors required to go out the front exit. The maintenance shell around the brig feels a little tacked on too. I freely admit that I'm not a big sec player though so I won't condemn it, you should get someone who is truly passionate about the department to comment more.

@Aurx That's how AI cores are designed, that's why shunting exists. Anyone with a full set of tools can get into the Box core, and you just listed the things necessary to wreck the meta core. AI cores are not supposed to be ultimate dungeon fortresses. Just like anyone with a beaker can slip a vampire, anyone can participate in breaking into the AI core on Box. The supercooling and EVA component actually make this AI core much more fortified than that one, only members of the crew with hardsuits can participate. That makes a substantial difference in malf - especially because acquiring a suit for those without one when the AI declares delta need to run to the opposite side of the station, brave AI booby traps, and get a suit, then come back. If the AI kills everyone with suits, they can just toy with the remaining crew.

**Comment by Shadowmech88** [comment]
![donutcomparison](https://cloud.githubusercontent.com/assets/3991927/23503258/81322b52-ff00-11e6-821e-73042277aeac.png)
A rename might be in order. It doesn't really resemble a donut at all anymore.

**Comment by Zth--** [comment]
Box2 :wink:

**Comment by Ephx1** [comment]
We can call it box 2 once we play it every single round and half the server screeches if it's not the map being played.

**Comment by Kurfursten** [comment]
@Aurx What are you talking about, no one assaults the Box core through the upload. It has weakpoints from the meeting room and captain's office that are much more appetizing because there are no turrets or blast door at all. Same thing on meta, in fact it's impossible to go through the main entrance (blast door + emitters) so you're forced to attack it from the side. Again, just one-wall thick.

**Comment by Aurx** [comment]
@Kurfursten 
Reading comprehension, man.  People in the upload derping around means the AI is hearing turret noises already and doesn't get the "OH SHIT MY TURRETS ARE ON PANIC" normal to core breakins unless it's paying careful attention to the sounds.  
And Meta is fine because the turrets there have decent fields of fire.  Though I do still see 'tards trying to go in the front door on Meta.

**Comment by Kurfursten** [comment]
Just remove the space and enlarge the core so the turrets have a better FOV then

**Comment by kilozombie** [comment]
![re e e](https://cloud.githubusercontent.com/assets/6062247/23539406/026ff430-ff90-11e6-9832-83ce0f5e5cb5.png)
The middle pillar is one tile off center

**Comment by CptWad** [comment]
![image](https://cloud.githubusercontent.com/assets/3959840/23566367/692be0e6-0006-11e7-9585-c7c434c108d1.png)
hows this for a new AI core?

**Comment by Kurfursten** [comment]
Looks good to me

**Comment by Aurx** [comment]
Yep, that solves it.

**Comment by Lokiamis** [comment]
No escape pods?

**Comment by Lokiamis** [comment]
-Atmos hardsuits may as well be the assistant hardsuits because they're 1 airlock and 2 tiles from the main hallway
-For an officer to get into space they'd have to run all the way to the secure armory (pray there's a warden around) for a suit and then run all the way to cargo maintenance which seems to be the closest airlock to space they'd have access to
-The only public space airlocks are in escape (which is also arrivals) and the one in cargo maint. Even engineers have to use solar airlocks to get outside.
-Bartender just barely has visibility on half of his tables from behind the counter and it looks like it'll be low room. I expect suicide rates to skyrocket here.
-Morgue to kitchen pipe is hilarious
-No antique in captain's quarters

**Comment by Kurfursten** [comment]
I have mixed feelings about the airlocks on the gas miners

It makes stealing a plasma miner joke tier difficulty, especially as an engiborg. You could do it in 5 seconds and 4 of those would be unwrenching the miner.

The mostly-done SME that is far from the middle of the station seems to imply that only idiots would ever use the singulo. Should we even have the singulo there? I know it's a tribute to the original donut, but as an engineer I honestly can't imagine a situation in which I don't yell at someone for setting that up. It's guaranteed disaster tier if it gets loose, at least on Box and Meta there's a chance of a "glancing blow" where it just takes some maint or fucks off to space entirely.

**Comment by Aurx** [comment]
MoMMI nest could use an airlock.  Sometimes you want to store draggables, or build a machine there then move it out.  
I like that there's something on the other side of secmaint, meaning that people can have a valid reason to be in there. 
There is literally no valid non-antag reason to set up the singulo on that map, given how done the SME is and how devastating a singuloose will be.  
The fore half of engineering appears to be completely isolated from the powernet and thus utterly reliant on a wire patch job or the singulo.  
The SME and AME appear to be wired straight into the grid.

**Comment by CptWad** [comment]
Ok update since its been a few days

>Updated AI core
>Updated much of the hallways. adding missing doors, APC's alarms etc.
>added missing art storage door
>added external airlocks near sec maint which were also near sec maintenace doors, allowing officers to reach space shortly.
>In that vein, added more external space airlocks
>Removed superfluous racks and added two flashers
>Added pixel displacement to various stacked items, medkits, armory guns, stacks of materials, boxes. 
>Unfucked the wiring in aux engineering
>Removed Airlocks for gas miners since a very good point was made
>Made SME setup slightly more annoying. Should take some 30+ minutes for a mommi to set up since none of the scrubbers/injectors are set up and will have to me multitooled
>Returned the Mommi door. Bolted one side since I cant trust idiots.


As for points, I was hoping that auxiliary engineering would be a headache in the aims that the singlo would be set up at least at the start. Given you can turn off a singlo once you have a safer engine online.

I have also been working on the upcoming mining asteroid stuff. Lots to do but it will be done

**Comment by Kurfursten** [comment]
Bear with me but I think I had a stroke of brilliance. What if, instead of a singularity, the center of the station contains a preset shield generator room, maybe even with some portal SMES ports so you can b-b-b-back that extra power up.

>Meteor event
>Already running MEGAWATTS through the engineering circuit
>Expand shield to protect entire station
>Profit

**Comment by CptWad** [comment]
careful mentioning meteors summons dylan from the grave

**Comment by Lokiamis** [comment]
Donut when

**Comment by Kurfursten** [comment]
You know Cpt, I was looking over this another time and one thing I noticed was a relative dearth of maintenance rooms. That's something people are going to want. There are the classics to fall back on of course

>Fire closets
>O2 pressure tank storage
>Storage room with heaters/air conditioners
>Incinerator
>Ghetto [department]

Another one I was thinking about would be the electricity equivalent of the O2 pressure storage rooms, put a portable SMES charging room somewhere far from engineering on the station, so you can go there and enable backup power if the main SMES get eaten by a singularity or something similar.

**Comment by CptWad** [comment]
theres already an incinerator, and I did try to fill up maintenance with _stuff_ where I could. 

as for the map itself I was taking a break for finals week and will be back at work eventually
Currently, I was working on mining station nonsense. So far so good.

**Comment by Kurfursten** [comment]
I don't see a radio transmitter room. That space next to the ghetto bar might serve, close proximity to a jukebox is usually desirable.

**Comment by CptWad** [comment]
![prisonstation](https://cloud.githubusercontent.com/assets/3959840/26021719/a733fb20-3748-11e7-9074-695755066893.png)
![scisat](https://cloud.githubusercontent.com/assets/3959840/26021721/a8210faa-3748-11e7-89e9-b1b9a159f515.png)
![voxstat](https://cloud.githubusercontent.com/assets/3959840/26021722/a93a6940-3748-11e7-8fe6-b9325810ec24.png)
soon

**Comment by Kurfursten** [comment]
Put only emergency O2 tanks in perma, so they have to keep coming back for refills

Discourages mining straight to space and floating off

**Comment by CptWad** [comment]
Theres rwalls containing them, dug through the asteroid

**Comment by CptWad** [comment]
![image](https://cloud.githubusercontent.com/assets/3959840/26022940/9237d872-3766-11e7-869d-596495d4849d.png)

**Comment by CptWad** [comment]
cool so I finished everything now to test it and make a pull request

**Comment by BobdaBiscuit** [comment]
ye boi

**Comment by Kurfursten** [comment]
The asteroid mapping seems much more awkward than the rest of the map.

>Research outpost seems very disjointed, long wide hallways
>Rooms don't feel organically placed, nor the stuff in them naturally oriented. This is a side effect of copy/paste that I'm guilty of myself.
>Brig is about twice as big as other brigs because it has two armories (one on station, one on gulag),  plus normal small cells on both the main brig and gulag brig, two brig medbays - again one on each
>What's up with the extra large pods? Made even stranger because there aren't any on the main station. A little screwy with balance since an antag can't sneak out in the secpods just by hacking a door, needs to steal an ID for the shuttle. Meanwhile no one can use those off-station pods in the event of a cult major victory.
>Why does science get pods at all?
>Where is the mining station?  I see there's a shuttle on the main station that should go to a mining post, but I don't see an actual mining post. They don't have brig access for the gulag's ore machine and none of the other stations have an ore machine.
>All of the Vox outposts have a general theme, so it would be nice if you could find a way to make this one feel different too instead of so similar to Box's.

I'll give more feedback if I can think of it

**Comment by CptWad** [comment]
there is mining but its the same as boxes since making more shit from scratch was painful, expect very little difference. 
Yeah lots of copypaste but I did make sure it all works in the end. Sci feels sloppy but its grown on me? I dont know how to explain it, its ugly and thats why I like it?
Pods for the new areas. Theres a pod in engineering still that is easier to sneak into than the box's eng pod
Theme for this vox outpost was inside an asteriod. You have a fair point so ive gone and made that a bit more obvious 
![image](https://cloud.githubusercontent.com/assets/3959840/26029997/12c82b30-37f9-11e7-86d6-6f8d24151aca.png)

**Comment by CptWad** [comment]
also 
![image](https://cloud.githubusercontent.com/assets/3959840/26029998/3d21cd6e-37f9-11e7-9dee-6fcd920ccf06.png)

**Comment by Kurfursten** [comment]
Maybe you should get feedback from other people. I think most of the original work you've done (on the main station) looks good, but the asteroid structures are generally very weak and people will complain about the copy/pasted, awkward rooms and halls. I know, I've lived that. I just want to save you the grief.

As for the Voxpost, that was more or less my point -- its theme is the same as the Box outpost. Both are embedded in an asteroid, you pasted over several rooms as well as the Box trade shuttle, and gave it all the same amenities. For example, bees and xenobotany machines are only on the Boxpost, meta gets all the medical research machines, but no radio and the worst botany, deff has no grinder but in exchange has an ore furnace and roundstart autolathe.

Make you could set them up with a general fab+DA, plastic seeds, RPED, and a few tier 3 parts they could analyze and copy. Then they could sell tier 3 parts as a gimmick for that base instead of having a fancy botany. Or you could make it entertainment oriented, include every clothing machine and other exotic clothes (like rare stuff that spawns in spessmart), all the big band crate instruments, and turn the ship into a mobile theater with curtains and the like. These are just examples, you could probably come up with something better and more original.

**Comment by CptWad** [comment]
rip this theres a PR now
