### ISSUE TITLE
Traders get too much shit (on certain maps)

### ISSUE THREAD

**Issue by Diavill** [vgstation-coders/vgstation13#15832]
As per the wiki (http://ss13.moe/wiki/index.php/Trader) the vox on certain maps get a bit too much for feathery jews that live in dirt and squalor.
I feel, if traders want a pimped out home, they have to work for it, or you know, ~~steal like niggers~~ trade shit with the crew to get it. Some variability between maps is fine, but some of the equipment they have is just way too good for jewbirds.

Defficiency and Bagel all have chem dispensers for the vox, an extremely powerful tool that they shouldn't have by default. Bagel and meta both have genetics, which makes sense on metaclub since the outpost is some wreckage commandeered by the jewbirds and had medical equipment on it but bagel doesnt really need it. For "lore" reasons I guess the metaclub chem dispenser can stay. 
Why the FUCK does the deff outpost have all three bar machines, you think you're living the high life you piece of shit bird? Vox enabling mappers begone.
Why do they get sec vends on every map but Bagel? Why give them a vend that specifically is for collecting balids and getting thicc? 

I might be missing a lot more with the randomized loot pools and stuff but these things seem out of place for the trader birbs, in my view.

**Comment by Konater** [comment]
>lore
lol

**Comment by Durgen** [comment]
iirc this the balance of the trader outposts (besides packed which I haven't played)

- Box: has extra large botany + Secvend + mining gear
- Metaclub has: full medbay (including chem) + very dilapidated + most newbirds won't find it
- Deff has: extra comfy + chem + secvend
- Bagel has: extra comfy + chem + some medbay + mining gear

If any outpost needs a nerf it is Bagel.

**Comment by jknpj** [comment]
Don't forget the smelting area

**Comment by Orangerush** [comment]
remove vox

**Comment by Durgen** [comment]
@jknpj added

**Comment by Unknown-as-Captain** [comment]
Are you honestly complaining about bar machines

jesus christ

**Comment by devlkiller0** [comment]
When was the last time you saw a trader actively collect valids? If anything, a better outpost would make them spend more time off the station which means the less time you have to see them around.

**Comment by Diavill** [comment]
Yes I am complaining about bar machines because those things are a luxury item, that you dont get for free as a bartender, meanwhile the fucking vox do.

**Comment by devlkiller0** [comment]
On **one** map and of all the times I have been trader on deff I have never seen anyone attempt to sell drinks and I've seen it used very very little.

**Comment by Kurfursten** [comment]
Shockingly, I agree. I've commented on this before, actually. This may seem strange coming from the guy who made Vox botany, designed the Vox outpost on Box, coded the Trader PDA, and recently argued against a nerf to trader magboots, but I actually do believe in a balance and certain aesthetic for Vox.

If it were up to me, I downgrade Deff and Bagel a bit more so that they don't have so much of *everything*, and bring Meta up to livable levels with quality of life changes like moving it to a Z-level that has radio (or at least giving them a transmitter) and making the dock not awful. Deff's exceptional perk of getting a mineral furnace is mostly ignored because they get random maintenance loot, Russian gear, bar machines, chem dispenser - don't even have to put together your autolathe like on other maps, it's there roundstart.

Use purely as an example of aesthetic, luxury items like the bar machines go against the general aesthetic of Vox as scavenging. Why not the new off-license soda machine instead?

**Comment by Riekland** [comment]
antag-only vox when?

**Comment by Kammerjunk** [comment]
>Whine and whine until vox becomes a non-antag roundstart race
>Slowly normalise vox until they get equal treatment to humans
>Give them their own species-unique job to live on the relatively unused outpost on the roid where (most) tators will have a harder time getting to them
>Not a lot of complaints because it's just going to be three poor man's miners on a shitty rundown outpost
>Traders start breaking into the research outpost all the time for the chem dispenser (and other loot) WHOA WHO COULD HAVE GUESSED
>Metaclub traders, the only map which didn't have an outpost for them but instead just had a crashed shuttle, get their entire own station in space
>Traders get immunity from tator antag, meaning tators won't have a much much harder time just because their target wanted to be a furry and also meaning traders won't be in risk of anyone (maybe excepting raiders and in rare cases gimmick ops) raiding them to get their greentext
>Deff outpost overhauled
>Slow small to not so small changes to Box outpost (bigger hallway, bigger botany)
>Trader vending machine gets added - turns out if you give people the option of vending a Bag of Holding, they'll keep it
>Box outpost overhauled
>Today, Traders/Merchants/**_Vagabonds_**/Travelers are equipped so that they need never trade, sell, wander, or travel - not just to survive, but to research for themselves

Megamaw is nothing in the face of vox.

**Comment by yclatious** [comment]
So, we all generally agree there is some level of issue with how vox have been pampered into normalcy compared to what should be the stereotypical raiding/theiving/trading race they are known as and how most vox players are indeed pampered lil shitkens who both don't deserve all this good stuff and are entitled shits.

If any other vox metaclub members want to pitch in and tell their damage control version, nows the time.

**Comment by Durgen** [comment]
@yclatious https://www.youtube.com/watch?v=xzpndHtdl9A

**Comment by yclatious** [comment]
@Durgen Thought the irony and the joke tone was kinda obvious, guess not.

@devlkiller0 I don't think the argument here is the exploitation of the resources given, so much as they have them to begin with, regardless of how abused they may or may not be. Im of the personal opinion that stronger stuff should be damaged/missing pieces, like a chem dispenser perhaps not being completely out the roundstart realm but instead a frame that needs a lot of parts, more for the sake of thematic coherence rather than under "this shit has been abused for tons of time and nobody has nerfed it because they were too damn lazy" tier, CAW magboots being a prime example.

**Comment by eatdembeanz** [comment]
I'm totally for any machines more advanced than a vending machine being reduced to a frame and a circuitboard, but you're delusional if you think trading with the crew for things you can trade to the crew is something that people actually do.

One way to make it so that Traders can have their cake and have to work for it too is to replace the Chemdispensers and Russian Vendors and smelters and shit with empty machine frames, and hide their respective circuitboards somewhere on the asteroid in pregenerated pseudovaults. If that bird wants his shitterjuice machine, he's gonna have to crawl along the outside of the asteroid and snatch the parts from the bottom of a pile of Hivebots.

**Comment by CptWad** [comment]
Many of you are unaware that vox traders on bagel WERE nerfed already

**Comment by CptWad** [comment]
see #15728
they dont even have an autolathe on bagel

**Comment by SonixApache** [comment]
put trading outpost on Z-2
make it shit
make traders a random event that polls ghosts rather than a roundstart job

**Comment by SarahJohnson489** [comment]
Diavill, go ahead and overhaul then create more things they have, can make, and can find that people would actually trade for first instead of just yanking the rug out from under them when shittags are ending rounds lightning fast until the trader just quits or retires solely to vault fishing. Flavor had to give way to gameplay for good reason.

**Comment by eatdembeanz** [comment]
If you want to give Traders more stuff to trade, porting the NPC trading system from Bay would go miles to balancing and giving in-universe reasoning for it. Like, give the Trading Shuttle a new destination to a massively trimmed-down miniature Spessmart with randomized stock. Traders will need dosh to buy them, which means they'll have to actually do some trading if they want cool toys.

**Comment by Kurfursten** [comment]
Unclear if it applies anymore, Bagel doesn't exist, Meta has an entirely different outpost, tons of Trader content happened since then. If you still care make a new issue up to date.
