### ISSUE TITLE
Summon Cultist (and presumably Free Cultist) list both dead and living cultists and don't bother to distinguish the two.

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#16664]
Something that's bugged me for some time but I kept forgetting to mention it.

**Comment by Knightkiller11** [comment]
Summoning a dead cultist body could have some uses to be fair, maybe their body has something useful on it, maybe you really, really need a dead body to ressurect someone into. That kinda stuff. 

I am up for adding a way to distinguish the two though, even though that could provide information they would not know otherwise. (i.e. that Cultist x is dead)
