### ISSUE TITLE
Maps have two chemist slots.

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#17306]
is there truly a need for more than one

**Comment by SonixApache** [comment]
two stations, two chemists

**Comment by Aurx** [comment]
When you consider the frequency of "Dude space drugs" chemists and "Dude lube and grenades" chemists, I'd argue yes.  

Of course, we all know that argument doesn't hold because everyone and their mother would rather break in or law 2 in and make their shit themselves than ask the chemist to do the job they signed up for.
