### ISSUE TITLE
Spread Blood jectie exists for Cult.

### ISSUE THREAD

**Issue by Allspice** [vgstation-coders/vgstation13#18113]
Spread a bit of blood, convert a few lads, TOQ-LYR RQA'NAP somethingsomething

This "issue" is more asking if and how it should be changed, because the blood-convert pairing is pretty underwhelming and noninteractive for ending the universe. A few possibilities: Remove blood as a possibility and require Convert and Sac every time; require all three; increase considerably the amount of blood required on-station; implement a different objective; whatever. Also, if the objective is made harder, I'd like to buff EMP and Blind to make them less trash, and perhaps give cult hoods flashbang resistance.

**Comment by Blithering** [comment]
Other ideas for mixing up the blood objective: 
Make it require certain people's blood to be spilled, sorta like a mini sacrifice
Have certain departments as targets for bloodening
Blood patterns? not sure how it would be tracked but drawing a giant rune in blood smears would be a laugh

**Comment by Kurfursten** [comment]
I think the blood objective isn't bad as an "act one" objective necessarily. In some ways it makes aesthetics tangible. A station drenched in blood is one that feels like it's decaying. The problem is a matter of scale. When you only need to cover 120 tiles in blood... that means you can just butcher chickens in botany and be done. In many ways a more demanding blood objective, say 1000 tiles, would be far more noticeable than a sacrifice objective.

**Comment by Inorien** [comment]
>sacrifice chaplain only happens if there's a chaplain
>cover tiles with blood only happens if there's a janitor
?????

**Comment by SirSkeleto** [comment]
blood in maint doesn't count?
