### ISSUE TITLE
drag damage is a bad feature and was disabled for a reason

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#19122]
These are my points from many hours of both observing and of playing Medbay.

### It penalizes the wrong person
Drag damage penalizes the wounded person and Medbay for the carelessness of the dragger, who is almost universally apathetic and unaccountable for his mistake.
Most people just don't care or don't remember that drag damage exists, it's somebody else's problem, and then they almost NEVER hear from it again. This happens often even with silicons, who should be the most concerned about it.
This is something that you can appreciate the most if you observe a lot. Also, I think this is the most dooming part of drag damage, because it can't exactly be fixed <sup>unless you bring back that bug that made the dragger get damage instead of the dragee</sup>

### It's inconsistent
Drag damage only applies if you had brute damage. You can have one guy with a mangled foot and one guy dying from toxins, both roughly the same on the triage scale, and only one of them will suffer drag damage if pulled. It's very arbitrary on gameplay terms and I think feeds into point 1, if you drag two dudes and nothing happens to them you'll probably care less next time.

### It's disproportionately damaging
It does a lot of fucking damage and it's the annoying to fix kind of damage
In terms of "how long it will take Medbay to fix that", drag damage is often just as bad or even worse than the original injury. And we're comparing "intentionally stab someone four times" to "make the small mistake of not fetching a locker", so it feels even more out of place.

### It's really fucking annoying
When you need to drag someone three tiles from a sleeper to cryo and you also need to fumble buckling and unbuckling them or their cranium fucking splits open the tedium of it starts to grate on you and you're probably starting to hate the Paramedic's job a little more every passing day just for indirectly causing this plight upon you.

#### I am not opposed to adding difficulty to Medbay, but I feel strongly that drag damage in particular is a terrible implementation of difficulty.

**Comment by brndd** [comment]
Would it be possible to make roller beds function in a way that clicking on the bed while someone is on it automatically buckles them to it and raises the bed? This would make it marginally easier to use them, as it requires less accuracy than dragging their sprite onto the bed.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Sure, but I don't think that would help much
And that only applies to point 4

**Comment by DrSnips** [comment]
I'd like to add that and also promotes [speed]cloning due to the sometimes super heavy blood loss (I consider anything <75% heavy loss). I'd rather see medical use the defib before anything else but the blood loss fucks with the ability to use the defib. Refilling their blood to get them within defib range is fine up until you need to do this several times to multiple people.

**Comment by Accipitermaris** [comment]
Also lags the heck out of my client after a certain point because each bloodsplatter caused by harmdragged bodies are always the big type that create footprints & the bloodsplatters themselves are fairly frequent

**Comment by ShiftyRail** [comment]
This will cause the Cult's spray blood objective to harder to do, but spray blood is already a formality

**Comment by Reviire** [comment]
I don't mind drag damage in theory, but it definitely needs some heavy big changes. I think it'd be much better as something that hit you later, rather than now. Not sure if this would require big changes, but maybe steadily increase your woundage over time. So if you're able to get someone there and quick, you're not going to see any changes. But if they're left around for 10 minutes or more, the damage keeps getting higher and they start getting fucked.

Rather than the instant moved 5 tiles, is now dead.

**Comment by bathosbathtime** [comment]
Feels like a good time for a server poll.

**Comment by Pathid** [comment]
@SonixApache Wasn't there an earlier version that would give you a warning message as soon as you started the pull on somebody? What happened to that?

**Comment by SonixApache** [comment]
@Pathid [code/modules/mob/mob.dm#L1057]

**Comment by Jeroen52** [comment]
What if it only damages people whenever you're on harm-intent?

**Comment by Dacendeth** [comment]
I wish drag damage only happened when someone had an open bleeding wound.

**Comment by SonixApache** [comment]
@Dacendeth well, yeah, it does.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
If the intent of drag damage is to reward prepared rescuers (i.e. give the paramedic a reason to exist) you could also accomplish that by making it inconvenient for unprepared rescuers rather than lethal for the wounded guy
Silly example but to get the point across: dragging a lying person makes you a bit slower unless you use a rollerbed

**Comment by Dacendeth** [comment]
@SonixApache then why arnt plasmemes immune to it then? The damage even gibs their limbs I think.

**Comment by Tokanova** [comment]
make it a crime in space law to drag an injured man around, a crime akin to assault and battery with a deadly weapon.

**Comment by jknpj** [comment]
I really dislike how abusable it is. I saw xenos abusing it once and it was even more disgusting then regular disarm+slash because they were killing people while avoid shotguns

**Comment by Chazach** [comment]
@SonixApache 
>splint or field amputation

This is such a useless statement it may as well not have been written. No-one has splints ready to hand and a field amputation would most likely just end the guys life right there from brute accumulation or blood loss.

**Comment by Killette2** [comment]
@DrSnips just make it so clones have zero blood to fix the clone issue

**Comment by SonixApache** [comment]
1: Could work, but 3.8 already pulls it from walking, and voxman himself already made it so that click&dragging someone from a bed to a machine re-beds them afterwards
2: It's limited to whatever the limb's max is, and lowers that to limbmax -6 in 3.8
3: Good point, should probably add that.

**Comment by DrSnips** [comment]
I'd actually be really happy if there was some cap on the amount of damage per limb. Im not sure if it's been removed since but I remember heads and limbs flying off because of dragging since the damage was all on one part. While that's a good step in the right direction I'm still going to have to see how blood loss ends up being.

**Comment by SonixApache** [comment]
Cap is max limb damage, and will be max limb damage -6 in the update that's hovering around. I've seen the exploding thing myself, and it `shouldn't` happen, but it does, so that's why that change was made.
Blood loss should also be a lot less bad, though as I always say, biggest cause of bloodloss is regular bleeding.
