### ISSUE TITLE
(Datums Changeling) Succing humans spawned with the "Spawn" verb breaks succing.

### ISSUE THREAD

**Issue by Irradiation** [vgstation-coders/vgstation13#19562]
Humans spawned with "Spawn" Human don't actually get husked, die or whatever when succed. The proboscis stabs them, but no fluid get absorbed. Because the fluids don't get absorbed, the succ never ends and thus you cannot succ anything else.

**Comment by SGuivenne** [comment]
The S U C C never Ends!

**Comment by MadmanMartian** [comment]
was presumably fixed by  #19543 as can not reproduce with given instructions of "Yeah I jumped into him as a ghost to initialize his mind, then succed him and I couldn't suck anymore"
![proofs_of_suck](https://user-images.githubusercontent.com/30557196/45933730-a8039800-bf8a-11e8-901c-3e0c257832e5.PNG)
