### ISSUE TITLE
Supermatter shard doesn't radiate when shot at by emitters

### ISSUE THREAD

**Issue by soyconsumer** [vgstation-coders/vgstation13#20554]
^

**Comment by Kurfursten** [comment]
Unable to reproduce on live

**Comment by soyconsumer** [comment]
Like 2 rounds ago on roid I could just walk around the SME room all day without a radsuit and take no damage

**Comment by Kurfursten** [comment]
The SME only puts out rads with in 3 tiles unless something is thrown into it. That's why the room is designed like that. It has always been that way, it's a feature. Outside of the shard chamber but inside the SME room you can still get toxified by hallucinations if you forgot mesons.

If you weren't getting radded inside the shard chamber itself that is a problem.

**Comment by soyconsumer** [comment]
Oh well, seems like I remembered it wrong
