### ISSUE TITLE
Blink needs a nerf discuss how here

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#21498]
Deadass at least 80% of wizards take blink because it's so good.

My opinion:
 * The unupgraded cooldown is way too short. Jaunt used to be the old "get out of stuns free" card and that one didn't have a 2 second CD for 20 spellpoints.
 * Perhaps it should require an upgrade before it generates smoke.

**Comment by boy2mantwicethefam** [comment]
it doesn't, people take blink because it's a reliable way to get out of trouble immediately in the age of ballistics meaning a death sentence for antags, especially wizard

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
People take it because it's so ridiculously good compared to literally anything else

**Comment by Dacendeth** [comment]
it generating smoke really devalues the smoke spell that all it does is make smoke.

**Comment by boy2mantwicethefam** [comment]
If anything, wizard should require something to retain their survivability, maybe a healing spell?
Few people take jaunt due to the long cooldown without investing points in it and the walking speed wizards get when jaunted, jaunt could get buffed either with a shorter cooldown or allowing running speed
Blink could also be nerfed by whitelisting space tiles, which means wizard could accidentally teleport into the cold darkness of space and they would require a hardsuit (now that I think about it wizard hardsuit shouldn't have a slowdown but that's gonna be a PR made by me for another time, either a slowdown or giving the wizard nobreath to compensate for usual lack of oxytank)
There's also the possibility of increasing spellbook points to make the wizard a more dangerous opponent altogether
These are a few ideas that could be reliably implemented
@Dacendeth pretty sure the smoke it generates is choking gas, which means people inside the smoke drop whatever they hold in their hands

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I think we can agree on the following:
 - Wizmen have few survivability spells
 - Blink is BY FAR FAR AND AWAY the best survivability spell of them all
Wizzies seemed to get fine for years and years without crazy good survivability spells but if they are to have good survivability spells, then Blink should be on the same level as the rest, not 3 levels above

**Comment by Irradiation** [comment]
>maybe a healing spell

Oy Vey, buy a Healing Potion goy!

**Comment by boy2mantwicethefam** [comment]
Other survivability spells can always be upgraded 3 levels above to be as powerful as Blink :smile:

**Comment by MadmanMartian** [comment]
I have a fun idea; blink drops a portal from where you teleported, leading to where you teleported.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Elaborate on that

**Comment by ShiftyRail** [comment]
Blink doesn't strike me as terribly overpowered, just overused and a bit uncreative
It becomes annoying with a meme autoclicker or something
Some guy in the thread once suggested that a wizard could choose between "backgrounds", with some backgrounds resteraining some spells/playstyles at the benefit of others.

Maybe it could lead to more crative wiznerds.

**Comment by Caboozles** [comment]
Just have blink make you honorbound or a derivative of. Gimmick wizards need it to avoid instant death. Wizards packing an arsenal or a soc should be more at risk.

**Comment by jknpj** [comment]
Make blink a shorter version of jaunt. You move through 2 tiles in a non-random, basically turning it into an evasion tool instead of a mobility one.

**Comment by MadmanMartian** [comment]
so, you blink forwards in the direction you're facing?

**Comment by jknpj** [comment]
Yes, teleports you to the direction you're facing/moving while respecting dense objects

**Comment by MadmanMartian** [comment]
>respecting dense objects

Could have the upgraded blink just let you go through walls, we moba now

**Comment by DrSnips** [comment]
Considering it's near instant or at least super fast a nerf to it's cooldown might be an option. The spell is currently used to spam infinitely making it near impossible to target them due to them using it faster than the allowed click speed and smoke. Another option would to give them some kind of drawback like vomiting for spamming it more than X times in a row.

**Comment by AI-Is-Rogue** [comment]
Raising the cooldown to 3 and lessening/removing the smoke could give people more opportunities to shoot them while the wizard still has an effective means of escape.

**Comment by Blithering** [comment]
Remove the check for space turfs
