### ISSUE TITLE
HasProximity() is extremely fucky for things that aren't mobs

### ISSUE THREAD

**Issue by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [vgstation-coders/vgstation13#21540]
Tested, for example, by adding PROXMOVE and a HasProximity() proc on a machine that simply said to_chat(world, "I have proximity to [AM]")

Works perfectly fine for mobs
Does not work fine at all for anything that isn't a mob

Throwing a bucket to the machine does not trigger proximity at all
Using admin tools to teleport the bucket to near the machine does trigger proximity correctly
Pushing a fueltank towards the machine does not trigger proximity at all
Pulling a fueltank behind yourself and walking towards the machine **makes the machine think it has proximity to the fueltank whenever it has proximity to you, even if the fueltank is 2 tiles away (??????)** (does not do this weird pull thing with mobs)

**Comment by Exxion** [comment]
I want to say "dude `forceMove()` lmao" but that doesn't really even remotely explain the last one

**Comment by Exxion** [comment]
Holy fucking shit
I fucking hate BYOND
Here's the problem:
https://github.com/vgstation-coders/vgstation13/blob/63e6f6083c1a51a9e2d0a6ddf8917ccb074c6d43/code/game/turfs/turf.dm#L172
Looks fine, right? Other than the redundant `as [stuff]`. But it isn't. If you don't specify a center for `range()`, it defaults to `usr`, *not* `src`
Therefore it only checks objects adjacent to the mob that caused the object to move, rather than the moving object itself
