### ISSUE TITLE
Please further segregate antags

### ISSUE THREAD

**Issue by aceedex** [vgstation-coders/vgstation13#22385]
[feature request]
Despite all the tweaking that has been done lately, I feel that dynamic is too damn wild and that the threat systems simply can't account for everything, making rounds very much unnecessarily busy.

I'd like it if someone with more intimate knowledge of game modes could do the following:
-should the roundstart ruleset be for for Cult, Malf, Nuke ops, revs or Blob, nothing else would be rolled for until an malf AI is dead, a cult is down to X amount of members during Y act, the blob is dead, the rev heads are dead, or the ops are down to one member.
-Instead of multiple antags for higher threat levels,  should those rulesets up there be picked, high threat should provide those rulesets with bonuses. An extra member/extra TC/Roundstart borg for Nukes, extra rev heads for revs, extra starting cultists for cult, extra starting points for blob, more AI points for malf and such.
-after those rulesets reach the points mentioned above, then can new midround antags start to show up
-If those rulesets arent picked, then it works as it is now

**Comment by Irradiation** [comment]
Maybe, just maybe, all the wild shit we're getting is due to the population enabling everything to go horribly wrong.

Also waiting only until an the current antag gets fucked to roll new antags is gay and is just bringing us back to the gold old days of pre-dynamic, except this time the system of "well, antag died, I hope admins do something" will be automatic.

**Comment by aceedex** [comment]
maybe, just maybe population spikes shouldnt turn everything upside down then, and the system shouldnt be fine tuned to something that can wildly fluctuate
If anything brings us back to the good ol times of not having code red at 12:10 because revcultblob I welcome it. No one seems to account that those antags specifically were absolutely meant to be round enders and "all hands on deck" scenarios

**Comment by Hoshi-chan** [comment]
I've said it once, I'll say it again: No more than a single "round-ending" antag should spawn at round start. Traitors and vampires should be able to spawn at any point. Also, blob should be midround _only_.

**Comment by codeungabunga** [comment]
Blob / cult / ops / rev should never exist at the same time.

**Comment by GlassEclipse** [comment]
I feel like most everybody agrees that the population-scaling resulting in more than large event is awful and chaotic. This can be fun like once, but every high-pop game lately just results in a clusterfuck. In general, I feel that there should be bigger threats, not more threats. Like the people say above, only allow there to be a single big threat and some minor threats 99% of the time. Increase the strength of these threats instead of adding more. Give cult another starting member or give extra telecrystals to the traitor. We can still have a dynamic threat system but it needs to be massively overhauled.

**Comment by ShiftyRail** [comment]
Having a discrete ad-hoc pop override is a bit silly and it does not do its job at all

**Comment by SGuivenne** [comment]
Having a blob, vamp, rev round or a malf AI --> Blob --> Supermatter Singulo round was fun precisely once.  After that it starts getting a bit cancerous.

**Comment by SonixApache** [comment]
I think blob ops is a fun combination.
I think a cult being thwarted / aided by wizardry is also pretty rad.
Malf also syncs up with blob relatively well.
Shit should be rare, though.

Traitors / vampires coming out of the woodwork to fuck over team-based antag modes is silly as fuck, however.
