### ISSUE TITLE
pAIs have access to the syndie channel

### ISSUE THREAD

**Issue by aceedex** [vgstation-coders/vgstation13#22922]
I like pai radio shenanigans but this one seems kind of silly

**Comment by Emilc4h** [comment]
If this is the round I'm thinking of, seeing as you were one of the Ops in it, I was a pAI being held by someone who'd taken one of your Operative's headsets because they let themselves get stripped.

You overhear other people's radios in proximity, and that includes a pAI overhearing their holder's radio and vice versa.

**Comment by aceedex** [comment]
Ah Ok. I though it was some radio shenannigans
