### ISSUE TITLE
We could use an upgraded plant anaylzer

### ISSUE THREAD

**Issue by Killette2** [vgstation-coders/vgstation13#2849]
An upgraded plant analyzer from RnD would be helpful for a better botany experience. Some things it could possibly do is (in order of importance)

-Tell exactly how much food and water the plant takes instead of using words such as a lot or little because there is still a lot of variation between a lot and a lot, where you may want to use one instead of the other.
-Tell what gasses it produces/absorbs.
-Tell what chemicals the fruit will provide. This one is not as important but could be good for the lazy botanist.
-Maybe analyze apiaries so bees can be further explored/understood? I understand that they grow from feeding plants (which is why I would like to know how much food plants take so I can please the bees without them dying from overpopulation) but I do not know how honey is produced and ways to manage bees besides constantly growing more plants.

I figured since more and more jobs are getting research upgraded items such as surgery and with the floral somatoray becoming a little lack-luster with all the new mutations and potency being near impossible to raise, that this could be a good feature.

**Comment by Midaychi** [comment]
Those sound neat but, knowing what I know about the xenobotany system, I don't think a lot of that would be very useful. I guess having a measurement of 'units of water' and 'units of fertilizer' per time period could be conceivably interesting but not very useful, due to all the plants working off a background nutrition and health system. All you really have to worry about is that there's fertilizer and water in the tray, and final amount doesn't really matter much. Each fertilizer increases the nutrition of the plant in the background per unit absorbed, depending on the fertilizer, either 1 nutrient per fertilizer or 2 for diethyl. Some of the fertilizers also count as beneficial reagents and confer a bonus to that plant per unit; Robust harvest or pure nutriment increase yieldmod and Radium or left4zed will increase (the somewhat useless) mutmod.

Knowing the exact plant gas exuding and absorption would be neat, but in my experience I've never seen it really matter much, and I have my suspicions to if the gas exchange code even works on vg. Tray lids can be closed to isolate the environment, and wrenched to a connector port, piped to another connector port with a tank so you can use an analyzer to figure out the gas exuded at least. 

Chemicals in the fruits would be neat I guess, but you can just scan the seed packet before you plant it.

Bees are basically magic.

**Comment by Killette2** [comment]
The reason I want to know how much nutrament plants take is due to bees. If your plants are all full because of the bees, the bees will eventually die because they have nothing left to pollinate or something like that. I have experienced it before where the bees did too good of a job feeding the plants (which is why I use bees) and collapsed because of this. If I were to find a plant with the maximum nutrament requirement, I would be able to keep bees alive longer or forever, as I've gotten lucky in some rounds with very high cost plants.

For seeds, you cannot scan to seeds to see what chemicals they will produce currently, that is the feature request to be able to scan the seeds or the plant.

For the gas thing, as soon as xenobotany came out, plasma in botany was very common as people planted many exotic seeds as possible without scanning for the good ones first. Seeds have a chance to produce or absorb any gas, including plasma, and there is no way to detect this until you plant them and see an air alarm going off.

**Comment by Probe1** [comment]
Having more depth through xenobotany would be cool.  I like the idea of alleles.

**Comment by 9600bauds** [comment]
I'd like a better way to know what type of gas a plant exudes, I wasn't aware of the connector port business though. can you explain the method better?

**Comment by Midaychi** [comment]
How it was originally designed is that plant trays were moved over to being atmospheric machinery. They should have a right click option to close the plant tray, which isolates the plant in its own atmospheric environment. Unless vg changed it somehow, you should be able to wrench it to a connector port and the tray will adapt the environment in the pipe into the tray.  This also works both ways; You can harvest gasses off the plant like this. This is why the baystation xenobotany lab has a connectorport and pipes/waste distro pump that nobody ever uses.

**Comment by Probe1** [comment]
An upgrade path that would be appreciated is information on the reagents inside the plant.  So you can know what it will produce when used on a grinder without having to grind it.  That'd save some work for exotic seeds.

**Comment by Killette2** [comment]
You can already do that with the fruit Probe1, by scanning a fruit with a plant analyzer you can see what chemicals are inside. The thing I'm asking is being able to do to the same for the seed before planting it so you don't waste time, but of course this would take RnD to make a nice item like that.

**Comment by Probe1** [comment]
It's funny I learned that this round.  I had never tried it before.  And here's your post, about the same time I was figuring it out on my own.

I'm all outta ideas then.

**Comment by Killette2** [comment]
Another suggestion for an upgraded plant analyzer - allow it to see exactly how much weeds and pest are in a tray. We used to be able to do this but are no longer able to, we can just tell when it's over the tolerance of the plant.

**Comment by ihadtoregisterforthis** [comment]
How far has this been fulfilled?

**Comment by 9600bauds** [comment]
Regular plant analyzers already tell you the gasses that the plant produces. More accurate nutrient and water consumption readings could be a thing, as well as accurate pest and weed levels, though I think showing chemicals before the plant is grown would completely trivialize exotic seeds. Somatorays are now not-shit so that covers the R&D aspect.

**Comment by gbasood** [comment]
Is there anything from this that needs fulfilling still?

**Comment by PJB3005** [comment]
Precise water / nutrient levels, and I'd like to add pressure to that too.

**Comment by Killette2** [comment]
I'd like an advanced scanner from RnD that could show the chemical output, and how much chems per potency. Maybe it could even read out what the plant will mutate into potentially (even though you probably have this memorized already)
