### ISSUE TITLE
Quick swap/equip (ctrl+e) puts gloves on your pockets

### ISSUE THREAD

**Issue by 9600bauds** [vgstation-coders/vgstation13#3371]
If you're already wearing gloves, ctrl+e puts your new set of gloves on your pockets rather than try to replace the ones you already have, which is mildly inconvenient so I'm making an issue on it like a little demanding cunt.

**Comment by ComicIronic** [comment]
Does it quickswap other kinds of items?

**Comment by Probe1** [comment]
@ComicIronic that's how it works for any pocket sized item.  

For it to happen you need an item that fits in a pocket, an item already in the slot you're trying to quickswap it into, and your pockets to be empty.  This comes up frequently as CE because he's got black gloves on at round start and will go to put on insulated ones right away.  If the players pockets are full the item will quickswap as expected (insulated gloves go from in hand to being worn and black gloves are returned).  If one of the players pockets is empty, it will instead move the item in hand (insulated gloves in this case) to the pocket instead of quickswapping it.  

This works the same for any kind of glasses, breath and sterile masks, and radio headsets.

**Comment by SkowronX** [comment]
Quickswap seems to iterate through pockets first.

**Comment by Exxion** [comment]
I always found this really annoying. It also happens to be one of those things that, depending on the existing code, could be either really easy to fix or a massive pain.
I guess it could be fixed easily in a rather shitty way if the code works the way that would cause it to be terrible to fix properly, but nobody wants that.

**Comment by clusterfack** [comment]
It's probably because quick equip just checks everything to see if it will equip. Since the pockets check is before the regular character checks, any object of proper size to fit in pockets will go into the pockets instead unless they are full.

**Comment by Exxion** [comment]
Well this is interesting
I just got around to looking at the code and the pockets are already at the end of the priority list.
BYOND handles lists really weirdly and the DM reference doesn't say how a for list statement iterates through the list. Maybe it iterates through backwards.

**Comment by ComicIronic** [comment]
This is more a discussion than anything else: should items be quickequipped to replace other items if they could go into pockets instead?

**Comment by 9600bauds** [comment]
Very much yes, why would you ever want gloves in your pockets?

**Comment by d3athrow** [comment]
make a hotkey that overrides the open slot check

**Comment by 9600bauds** [comment]
What's the function that handles this? I might look into it
