### ISSUE TITLE
power monitor doesn't report some power draws

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#33729]
[bugfix]
radio transmitters show up on the monitor, but don't show the powerdraw
same goes for the trader antique mattersynth

**Comment by Eneocho** [comment]
Radio transmitter is a bug. The mattersynth is intentionally outside of the power monitor's range.

**Comment by pedr69** [comment]
intentionally outside? you can still set its priority and see it in the menu, it just shows up as drawing 0W

**Comment by Eneocho** [comment]
It's not supposed to have it's priority be changeable (see #32613), since it can have effectively infinite load, and with a high enough priority, work as a ghetto power sink.

**Comment by jellyveggie2** [comment]
pedr69 is actually right about the matter synth showing 0W usage being a bug. 
On [antiquemattersynth.dm#L76](https://github.com/vgstation-coders/vgstation13/blob/0471421e9a28d6f362942470054f4b9ac7092462/code/game/machinery/antiquemattersynth.dm#L76), should be `return list("\ref[src]" = template)` to havethe monitor show the demand, charge amount and charging status I had loaded into the monitor template, not `return list("\ref[src]" = get_monitor_status_template())` which is ignoring the template I had just filled in and returning a blank one (0W on the demand field).
Also I just realized though I did put in the excess priority level on the synth and made it so that level looks like an interfacing error on the monitor, I failed to put in any mechanisms to keep it locked to that level. Same goes for the bypass level probably, but none ot the bypass devices (power sink, singularity beacon) are meant to show up on the monitor in the first place.

I went through all power machines and power connection components just a moment ago double-checking for any other "monitoring enabled" machinery that show as 0W on the monitor, final count is the radio transmitter, antique synth and also the wall shield generators (the ones in telescience).

Fix PR will be up in a moment once I'm done writing it up. 
I'll write up a fix PR to keep the mattersynth's level locked in a moment too.
