### ISSUE TITLE
space not visible through cameras

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#33956]
it's solid black, and sometimes the black also covers up other stuff
probably missed by #33871

![image](https://user-images.githubusercontent.com/18052467/210405572-bc2370cf-44ef-4331-81c5-203bc3884b85.png)

![image](https://user-images.githubusercontent.com/18052467/210405652-de92736f-23ff-4788-a105-8309d6aa885b.png)

**Comment by Exxion** [comment]
I still haven't gotten around to trying the camera console on my Windows machine, but I did notice that space and anything on it is invisible outside the area covered by your mob's `dark_plane`. You can see this if you zoom in as a ghost, as `dark_plane`'s scaling isn't quite correct. What's weird about this is that space is equally visible no matter what the `dark_plane`'s `alpha` is, as long as it's not zero. This does not have to do with the overdark system, as it still happens if it's disabled, but could still be caused by the plane rearranging from the same PR, I guess

I also notice that in the first picture in the OP, the *very same object* in two different places appears visible in one and covered in another. I have no idea why this might be. Lattices are also covered in the first picture but not the second. Is it that objects south of the camera aren't covered? But we're not using `SIDE_MAP` or anything.

Also, on an unrelated note, I noticed that a bunch of windows on Packed are offset by one pixel in various directions. You can see related lighting weirdness in the lower-left corner of the first picture. This specific thing is a mapping mistake (at least I assume it's a mistake), not a bug

**Comment by pedr69** [comment]
seems to work now
