### ISSUE TITLE
sneakycoded holomap fuzzying

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#34585]
#34579
https://github.com/vgstation-coders/vgstation13/blob/8151fe315a9052f19517810c65563e256b8ee363/code/modules/html_interface/map/station_map.dm#L162

**Comment by DeityLink** [comment]
I didn't put it in the changelog since the arrivals outpost didn't previously have Station Holomaps so only the very few people using the PDA Station Holomap app (and observers but those don't count) would have seen it. According to @Kurfursten Nanotrasen supposedly only realized later that they had built their station on a giant corpse, I think it's a nice way to keep some of the roid's mystic.

**Comment by pedr69** [comment]
yeah it isnt sneaky to me because i know what the snaxi/roid kraken looks like
but the players will see nothing about this in the changelogs once the serb updates

**Comment by DeityLink** [comment]
Well it's in the changelog now, but for new players who didn't previously know what it really looks like they'll be like "wait, what do they meant by "true form"?". I figured we'd want to keep small secrets like that out of the changelog but it's not a big deal for me either way.

**Comment by Kurfursten** [comment]
I feel satisfied that Deity has addressed this, but thank you for pointing it out for transparency
