### ISSUE TITLE
Emitter beams can't pass through windows to a shard if the windows are on the same tile as the shard.

### ISSUE THREAD

**Issue by Probe1** [vgstation-coders/vgstation13#3977]
If you make a supermatter chamber that is 1x1 tiles big the beams will stop at the window instead of passing through and hitting the shard which generates no power.  It looks like this.

![image](https://cloud.githubusercontent.com/assets/8550416/7216617/c4b3bc30-e5d3-11e4-9432-98fa522ab05f.png)

I'm not sure how to fix it.

**Comment by dylanstrategie** [comment]
Emitter beams are one of the buggiest pieces of code we have currently. It even surpasses the powernet and ZAS in completely unexpected behavior. The fact that there's still a way to crash the server with them, that can be triggered intentionally or not no less, is fucking terrible

**Comment by clusterfack** [comment]
Powernet aint buggy no mo

**Comment by Kurfursten** [comment]
@clusterfack This isn't a bug anymore, and I have a screenshot to prove it

![mini sme](https://cloud.githubusercontent.com/assets/9782036/10528557/8534a4ae-735c-11e5-89e2-18d16bb71286.png)

**Comment by Probe1** [comment]
" The same tile "

**Comment by FudgePucker** [comment]
@Kurfursten Problem with that picture is that we can't really see if your SME was working.

Can you rebuild it and see how much power is being produced by the collector?
Is a single scrubber really enough to prevent plasma from popping up?
I can't see the shard being active because you are wearing messons in this picture.

**Comment by Kurfursten** [comment]
Yes, but it doesn't matter (read Probe's clarification post in response)

**Comment by Intigracy** [comment]
Probe, what happens if you remove that wall?

I'm assuming the beam shoots through the shard.

**Comment by Probe1** [comment]
theres no wall in other screen shots

**Comment by Intigracy** [comment]
That's the only one you have that has the emitters right next to the shard like you're talking about in the issue report.

It's working correctly in the other image shown.

**Comment by BarneyGumball** [comment]
I did some testing and surrounding a shard on 4 sides with glass wouldn't let me hit it with an emitter from any range.

View Variables makes shows that the beam is connecting to one of the windows, rather than the shard.  Beams use `step()` as they extend out so I'm 95% sure this bug is caused by this: #11253

**Comment by PJB3005** [comment]
This bug has been around for a much longer time though, is the issue.

**Comment by BarneyGumball** [comment]
Hmm, I guess it's 2 separate issues then.  Can't really be tested until `Bump()` gets fixed anyway.

**Comment by Shadowmech88** [comment]
No longer exists.

![image](https://user-images.githubusercontent.com/3991927/67569682-22a26800-f6f5-11e9-8eb2-5e6e96bbd850.png)
![image](https://user-images.githubusercontent.com/3991927/67569990-f2a79480-f6f5-11e9-8055-9c2f236d2eb0.png)

Despite being in a glass box, the supermatter shards quickly began producing plasma when hit by an emitter beam. Placing the emitter directly next to the boxed-in shard worked as well.
