### ISSUE TITLE
(WEB REPORT BY: tersr REMOTE: 198.245.63.50:7777) Can't delete R&D data

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#4057]
> Revision (Should be above if you're viewing this from ingame!)

f644dddb05942ea37dbd2c20817d8f580e41c139

> General description of the issue
> Unable to delete or restart data on the R&D server
> 
> What you expected to happen
> To be able to reset illegal research to level 1
> 
> What actually happened
> Stayed at level one.
> 
> Steps to reproduce if possible
> do some research, try to delete it on the server computer.

**Comment by ComicIronic** [comment]
I'm struggling to understand what the issue is.
You had research at 1, tried to reset it to 1, and it stayed at 1?

**Comment by PJB3005** [comment]
I'm pretty sure you're able to delete R&D data, you'll just have to reset the R&D console by de- and reconstructing it, you can then delete the data from every R&D server

**Comment by 9600bauds** [comment]
You can reset the tech level, but it doesn't delete any of the actual designs you have unlocked by getting the tech level that high. And deleting individual designs doesn't work. Great.

**Comment by 9600bauds** [comment]
I give up trying to make this work. What the fuck.

**Comment by Shadowmech88** [comment]
After testing, it seems that deleting individual designs does not work because the design list in the server control console appears to be populated only with level 1 designs. Newly-researched designs simply do not show up to be deleted.
I assume deleting level 1 designs does not work because the computer instantly has a high enough tech level to re-learn the designs, no matter what its tech levels actually are.

**Comment by Shadowmech88** [comment]
After testing, deleting the design does not work if you still have the requisite tech level, as might be expected. However, even if you reset the tech level and then delete the design, it does not actually remove the design from R&D consoles, and the design can be re-uploaded to the R&D server via the sync button even if you still don't have the necessary tech level. Even if you reset the tech level, delete the designs, and then reset the progress of the R&D console, syncing the R&D console with the network then re-adds the deleted design back to the R&D console, despite it still not existing on the R&D server. If you then sync the R&D console *again*, the design is re-uploaded to the server.

**Comment by Shadowmech88** [comment]
I'm not sure how one would go about fixing this, since I don't know from where the console is retrieving the design that has, supposedly, been deleted from everywhere. I believe other R&D consoles don't update until manually synced, and although the connected protolathe has its own research datum, its designs never seem to change from the default list even when the console's do. I'm not sure the protolathe's research datum is even used.

**Comment by Shadowmech88** [comment]
The culprit does not seem to be data stored on the Centcomm R&D server. Even after physically deleting that server and its console, syncing the R&D console with the network is able to pull deleted designs out of thin air.

**Comment by Shadowmech88** [comment]
It turns out that the Robotics R&D servers contain a full copy of everything on the Core R&D server, for some reason. However, even after deleting the designs from the core server and both Robotics servers, syncing the console still retrieves the deleted designs. I put code in to display the name of every server being synced with, so there are no hidden extra servers anywhere as far as I can tell.

**Comment by Shadowmech88** [comment]
I found the cause.
It turns out that the Derelict R&D server does not just share a name with the station's Robotics R&D Server, it is exactly the same type. This means that it contains the same `server_id`.
Because `server_id` is used by the server console menu to determine which server to edit, this means that while the Derelict R&D console *appears* in the server list, it cannot ever actually be edited. Attempting to edit it simply opens the menu for the station's Robotics R&D Server.
Hence, when one deletes a design from the core server, then deletes it from the Robotics server, and then attempts to delete it from the second Robotics server, one finds that said design is already gone from the latter. I had assumed, due to the identical names, that they simply synced their contents, but the actual reason is that the second Robotics server can't ever be accessed, and clicking it simply accesses the first one.
When you then sync the R&D console, it pulls the design from the Derelict server, since it was never deleted on that server.

**Comment by Shadowmech88** [comment]
I'm going to go ahead and open a new report with the information more concisely laid out.
