### ISSUE TITLE
(WEB REPORT BY: kurfurst REMOTE: 198.245.63.50:7777) Adv Camera Issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#4264]
> Revision (Should be above if you're viewing this from ingame!)
> 87734707e12e85618c5532f25f6264abed6cce2f 
> 
> General description of the issue
> If a camera has "no response", you can access it by jumping to a different camera first.

**Comment by gbasood** [comment]
I think this is possibly exploitable anyway

**Comment by clusterfack** [comment]
Can someone verify this bug exists and works as described?

**Comment by mlgdatboi** [comment]
why did you leak his ip

**Comment by Exxion** [comment]
Just like the IP in every single other web report ever (until we removed that part of the web report), that is the SERVER's IP

**Comment by Shadowmech88** [comment]
I'm not sure under what conditions a "no response" reply would have been produced. The code currently does not contain that string.
However, assuming it referred to deactivated cameras, this bug seems to no longer exist. The advanced camera console currently does not show deactivated cameras at all; they are neither visible nor clickable, and so cannot be switched to.
