### ISSUE TITLE
Thrown glass shards (in mass) no longer fuck shit up

### ISSUE THREAD

**Issue by CptWad** [vgstation-coders/vgstation13#9225]
#### Description of issue

Lets say you hook up a disposal bin to shoot 50 glass shards at a prisoner for execution
it USED to instakill delimb people
it only does around ~150 damage now
intrestingly enough you can grab-throw people over 50 shards and that instakills people so stepping on 50 shards at once is more dangerous than 50 shards being shot at you
Tested with both regular shards and plasma shards
#### Difference between expected and actual behavior

50 shards at 15 throwforce is 750 damage
its only doing 150, usually less
#### Steps to reproduce

best way to do it is to spawn in 50 shard then use a trashbag to fill the disposal-bin cannon
#### Server revision

ffba5cdcc40bf1c573f7fc737136556594f9543d
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by DrCelt** [comment]
sounds like a good thing

**Comment by Killette2** [comment]
Is this due to the change of a shards sharpness or damage proc? That was probably overlooked when stepping on them, because I doubt the coder who changed the way you sharpen glass touched stepping on glass on the floor.

**Comment by CptWad** [comment]
yeah but my old clown gimmick of shard cannons is no longer feasible
in the before times
as for stepping on glass shards it should really only be two shards per foot as stepping on all 50 shards is nonsense

**Comment by Killette2** [comment]
I thought of something to solve your problem CptWad. I was planning on making a temple, but since that round seems to be going to happen never ever, try a mass driver button down a hallway. If pressed, a mass driver will throw spears.

Also stepping on 50 shards makes plenty of sense. If you walked barefoot on a huge pile of legos, would you only feel 2 of the legos?

**Comment by Intigracy** [comment]
Stepping on all of the shards registers correctly because even once it knocks you down it's still calling crossed().

When you throw them en masse at someone, the first like 13 will hit them, then they're considered knocked down because it obviously knocks them down, so the rest won't count as having hit them, even though they stop correctly for some reason.

**Comment by CptWad** [comment]
Yeah but what if they are strapped to a chair?
They should all hit right?

**Comment by Intigracy** [comment]
idk

**Comment by CptWad** [comment]
thing is the person I tested was against a chair.
they SHOULD all hit

**Comment by Killette2** [comment]
I do know however, since diona don't feel pain they can walk over hundreds of spiked fruits as mentioned before, which act as glass shards when barefoot and they don't get knocked down due to not feeling pain. With enough spiked fruits, say a full plant bag on a tile, their body becomes an immediate black tint (their blood) as it rips off all of their flesh and instantly kills them beyond crit and defib levels.

**Comment by Shadowmech88** [comment]
I'm not really sure whether this is a bug, or just a foreseeable effect of some kind of rework done on shards/throwing in general. 150 is still a fantastic amount of damage all in one shot.

**Comment by Exxion** [comment]
As far as I'm seeing, the calculation for thrown item damage has always been `throwforce * speed / 5`
Disposal chutes always throw items at speed 1
Therefore glass shards deal 3 damage each when thrown out of a disposal bin
50 * 3 = 150

**Comment by Shadowmech88** [comment]
Case closed, then.
